# Generated by Django 4.2.30 on 2026-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='当前库存')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品管理',
            },
        ),
    ]
